AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 900

Resources:
  Function:
    Type: AWS::Serverless::Function 
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          CSV_S3_OUTPUT_PREFIX: textract-csv-output
          CSV_S3_OUTPUT_BUCKET: idp-stack-python-sample-schademcdkidpstackpython-gnw5reia5742
          LOG_LEVEL: DEBUG
          META_DATA_TO_APPEND: DOCUMENT_ID,SOME_KEY
          TEXTRACT_API: LENDING
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.9-v1

